# {{- $fullName := include "fe-test.fullname" . -}}
# {{- $ns := include "fe-test.namespace" . -}}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/cors-allow-origin: '*'
#     nginx.ingress.kubernetes.io/enable-cors: 'true'
#     nginx.ingress.kubernetes.io/proxy-connect-timeout: '3600'
#     nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
#     nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
#     nginx.ingress.kubernetes.io/proxy-body-size: 500m
#     nginx.ingress.kubernetes.io/send-timeout: '3600'
#     # nginx.ingress.kubernetes.io/configuration-snippet: |
#     nginx.ingress.kubernetes.io/server-snippet: |
#       location ~ / {
#         if (${DOLLAR}request_uri ~* "seocache") {
#           # set ${DOLLAR}new_uri https://tmtrav-seo-dev.tma-swerp.com/render/${DOLLAR}scheme://${DOLLAR}host${DOLLAR}request_uri;
#           set ${DOLLAR}new_uri https://tmtrav-seo-dev.tma-swerp.com/render/https://${DOLLAR}host${DOLLAR}request_uri;
#           rewrite ^(.*) ${DOLLAR}new_uri permanent;
#           break;
#         }
#         if (${DOLLAR}http_user_agent ~* (googlebot|bingbot|yandex|msnbot|zbot|SkypeUriPreview|Discordbot/2.0|^WhatsApp|WhatsApp/2)) {
#           # set ${DOLLAR}new_uri https://tmtrav-seo-dev.tma-swerp.com/render/${DOLLAR}scheme://${DOLLAR}host${DOLLAR}request_uri;
#           set ${DOLLAR}new_uri https://tmtrav-seo-dev.tma-swerp.com/render/https://${DOLLAR}host${DOLLAR}request_uri;
#           rewrite ^(.*) ${DOLLAR}new_uri permanent;
#           break;
#         }
#         if (${DOLLAR}http_user_agent ~* (FacebookBot/1.0|facebookexternalhit|facebookexternalhit/1.1)) {
#           # set ${DOLLAR}new_uri https://tmtrav-seo-dev.tma-swerp.com/render/${DOLLAR}scheme://${DOLLAR}host${DOLLAR}request_uri;
#           set ${DOLLAR}new_uri https://tmtrav-seo-dev.tma-swerp.com/render/https://${DOLLAR}host${DOLLAR}request_uri;
#           proxy_pass ${DOLLAR}new_uri;
#           break;
#         }
#         proxy_pass http://$k8s_service_name.$namespace.svc.cluster.local:$service_port;
#         proxy_set_header Accept-Encoding ${DOLLAR}http_accept_encoding;
#         gzip on;
#         gzip_types text/plain text/html text/css text/csv text/javascript application/xml application/xhtml+xml application/json application/javascript application/x-javascript application/ld+json image/svg+xml application/vnd.ms-fontobject application/x-font-ttf font/opentype font/ttf;
#         gzip_proxied       any;
#         gzip_vary on;
#         gzip_comp_level 6;
#         gzip_http_version 1.1;
#         gzip_min_length 8;
#         gzip_buffers 16 8k;
#       }
#       location = /robots.txt {
#         allow all;
#       }
#   name: "ingress-{{$fullName}}"
#   namespace: {{$ns}}
# spec:
#   rules:
#   - host: $service_domain
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: "svc-{{$fullName}}"
#             port:
#               number: 

